source 'https://rubygems.org'

gem 'rails', '3.2.12'

#gem 'mysql2'
#gem 'sqlite3'
gem 'jquery-rails'
gem 'simple_form'
gem 'devise'
gem 'cancan'
gem 'mongoid'
gem 'redis'

platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
  gem 'activerecord-jdbcmysql-adapter'
  gem 'jruby-openssl'
  gem 'torquebox'
end

gem 'font-awesome-rails'
gem 'bourbon'
#gem 'requirejs-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'jquery-ui-rails'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.0'
end

group :test do
  gem 'cucumber-rails', :require => false
  gem 'capybara'#, '1.1.4'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'simplecov'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
