development:
  adapter:  mysql
  encoding: utf8
  database: chatapp_dev
  username: root
  password: root

test: &test
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: sqlite3
  database: db/production.sqlite3

cucumber:
  <<: *test